let player;
let playIntro = true;
let score = 0;
let scoreText;
let startGame = false;
let maxxdaddy;
let curScore = 0;
let bmd;
let bodyandlegs;
let head;
let awning;
let standing = true;
let corrector = 0;
let randomizer = 0;
let factor = 0;
let rotation = 0;
let guyRotation = 0;
let wobble = 3;
let fluctuation = 1;
let legs;
let body;
let bottle;
let leftArm;
let leftArm2;
let leftArm3;
let rightArm;
let drunkardWalking;
let drunkardStanding;
let falling;
let walking = false;
let gameOverText;
let highScore = 0;
let street;
let leftWall;
let rightWall;
let walls;
let streetTween;
let awningTween;
let leftWallTween;
let rightWallTween;
let timeToDrink;
let drinkCount = 0;
let drinking = false;
let drunkX = 0;
let wobbleThreshold = 3;