let player;
let playIntro = true;
let score = 0;
let scoreText;
let startGame = false;
let maxxdaddy;
let curScore = 0;
let bmd;
let streetShrink = 1;
let bodyandlegs;
let head;
let awning;
let standing = true;
let corrector = 0;
let randomizer = 0;
let factor = 0;
let rotation = 0;
let guyRotation = 0;
let wobble = 10;
let fluctuation = 1;
let legs;
let body;
let bottle;
let leftArm;
let rightArm;
let drunkardWalking;
let drunkardStanding;
let falling;
let walking = false;
let gameOverText;
let highScore = 0;
let awningShrink = 1;
let leftWallScale = 1;
let rightWallScale = 1;